"""Stage 7 — reconciliation. Cross-check the registries and report real drift.

    python -m ledger.reconcile                # print a summary, write a report
    python -m ledger.reconcile --no-write
    python -m ledger.reconcile --no-zotero

THREE TIERS — get this wrong and the report is worthless
--------------------------------------------------------
    cited       the citation set your manuscript compiles against   authoritative
    candidates  the pool you are still choosing from                undecided
    library     everything you read to build understanding          not tied to
                                                                    any one paper

"In library but not cited" is the NORMAL state. It is not a defect and this tool
will not report it as one. Flagging that gap buries the handful of findings that
actually matter — which is exactly what happened on the first version of this
report, where 45 perfectly healthy rows drowned three real ones.

「在 library 而不在 cited」是正常状态，本工具不会把它报成缺陷。把这个差额
报成错误，只会把真正要紧的那几条埋掉——本报告的第一版正是如此，
45 条健康记录淹掉了 3 条真问题。

FOUR DEFECT CLASSES — and only these four
-----------------------------------------
    X1  in cited, absent from library        cited but never logged as read
    X2  in candidates, absent from library   planned but never logged
    X3  a note exists, absent from library   the note ran ahead of the record
    X4  a pool member has no pinned citation key in Zotero    spine broken

Aliases are resolved before anything is compared. Without that, every key you
ever renamed shows up as a false positive.
"""
from __future__ import annotations

import argparse
import datetime as dt
from pathlib import Path

from . import common as C


def build(cfg: dict, use_zotero: bool = True) -> dict:
    reg = C.load_registry(cfg)
    cited, cited_src = C.load_tier(reg, "cited")
    cand, cand_src = C.load_tier(reg, "candidates")
    lib, lib_src = C.load_tier(reg, "library")
    vault = C.vault_notes(reg)
    alias = C.load_aliases(reg)

    zot, zot_err = {"by_citekey": {}, "by_doi": {}, "all": []}, None
    if use_zotero:
        try:
            zot = C.zotero_index(cfg)
        except Exception as e:
            zot_err = repr(e)

    def canon(k: str) -> str:
        return alias.get(k, k)

    cited_c = {canon(k) for k in cited}
    cand_c = {canon(k) for k in cand}
    lib_k = set(lib)
    vault_k = set(vault)

    # The pool is what may end up in the manuscript. Only pool members need a
    # pinned citation key; the rest of the reading library does not.
    pool = cited_c | cand_c

    return {
        "reg": reg, "alias": alias, "zot": zot, "zot_err": zot_err,
        "cited": cited, "cand": cand, "lib": lib, "vault": vault, "pool": pool,
        "sources": {"cited": cited_src, "candidates": cand_src,
                    "library": lib_src},
        # defects
        "X1": sorted(k for k in cited if canon(k) not in lib_k),
        "X2": sorted(k for k in cand if canon(k) not in lib_k),
        "X3": sorted(vault_k - lib_k),
        "X4": (sorted(k for k in pool if k not in zot["by_citekey"])
               if zot["all"] else []),
        # informational, NOT defects
        "pending": sorted(cand_c - cited_c),
        "unanchored": (sorted(k for k in cited if canon(k) not in cand_c)
                       if cand else []),
        "learning_only": sorted(lib_k - pool),
    }


def render(cfg: dict, d: dict) -> str:
    today = dt.date.today().isoformat()
    L: list[str] = []
    A = L.append

    A(f"# Reconciliation report — {today}")
    A("")
    A("> Generated by `python -m ledger.reconcile`. This is a **drift list, not a")
    A("> set of conclusions.** Whether to change anything is the author's call.")
    A("")
    A("## Tiers")
    A("")
    A("| Tier | Meaning | Count | Source |")
    A("|---|---|---|---|")
    A(f"| **cited** | what the manuscript cites (authoritative) | "
      f"**{len(d['cited'])}** | {d['sources']['cited']} |")
    A(f"| **candidates** | still choosing (undecided) | {len(d['cand'])} | "
      f"{d['sources']['candidates']} |")
    A(f"| **library** | read to build understanding | {len(d['lib'])} | "
      f"{d['sources']['library']} |")
    A("")
    A("**In library but not cited is normal, not a defect.** Reading widely does")
    A("not oblige you to cite widely.")
    A("")
    A("| Other registry | Count |")
    A("|---|---|")
    A(f"| Note vault | {len(d['vault'])} |")
    A(f"| Zotero top-level items | {len(d['zot']['all'])} "
      f"(pinned citation keys: {len(d['zot']['by_citekey'])}) |")
    A("")

    if d["alias"]:
        A("### Resolved key aliases")
        A("")
        A("| manuscript side | library side |")
        A("|---|---|")
        for a, b in sorted(d["alias"].items()):
            A(f"| `{a}` | `{b}` |")
        A("")
        A("> Without alias resolution every renamed key is reported as missing.")
        A("")

    if d["zot_err"]:
        A(f"> Zotero was unreachable, so that dimension was skipped: "
          f"`{d['zot_err']}`")
        A("")

    A("---")
    A("")
    A("# Defects")
    A("")

    def block(tag, title, keys, note):
        A(f"## {tag} {title} ({len(keys)})")
        A("")
        A(note)
        A("")
        A(", ".join(f"`{k}`" for k in keys) if keys else "*none*")
        A("")

    block("X1", "in `cited`, absent from `library`", d["X1"],
          "Your manuscript cites these, but your reading record has no entry for "
          "them. You cannot defend a citation you have no notes on.")
    block("X2", "in `candidates`, absent from `library`", d["X2"],
          "Planned as possible citations but never logged as read.")
    block("X3", "a note exists, absent from `library`", d["X3"],
          "The note ran ahead of the record. Add the corresponding library entry.")

    A(f"## X4 pool members with no pinned citation key in Zotero "
      f"({len(d['X4'])} / {len(d['pool'])})")
    A("")
    A("Counted over the pool (`cited` + `candidates`) only — the rest of the")
    A("reading library does not need a pinned key.")
    A("")
    if not d["zot"]["all"]:
        A("*Zotero not read; skipped.*")
    elif d["X4"]:
        A("Add a line `Citation Key: <key>` to the item's Extra field. Better")
        A("BibTeX then treats it as final. `python -m ledger.zot pin` does this.")
        A("")
        A(", ".join(f"`{k}`" for k in d["X4"]))
    else:
        A("*All pool members are pinned.*")
    A("")

    A("---")
    A("")
    A("# Informational — not defects")
    A("")
    A(f"## In `candidates`, not yet in `cited` ({len(d['pending'])})")
    A("")
    A("Under consideration. **This is not a problem** — you may well have decided")
    A("against citing them. Useful as a last pass before submission.")
    A("")
    A(", ".join(f"`{k}`" for k in d["pending"]) if d["pending"] else "*none*")
    A("")
    if d["unanchored"]:
        A(f"## In `cited`, never listed as a candidate ({len(d['unanchored'])})")
        A("")
        A("Already cited, but your candidate list never mentioned them — the list")
        A("may have fallen behind the manuscript.")
        A("")
        A(", ".join(f"`{k}`" for k in d["unanchored"]))
        A("")
    A(f"## Read for understanding only ({len(d['learning_only'])})")
    A("")
    A("Neither cited nor a candidate. This is your knowledge base doing its job.")
    A("")

    A("---")
    A("")
    A("## Suggested actions")
    A("")
    n = 0
    for keys, msg in ((d["X1"], "log the cited-but-unrecorded entries (X1)"),
                      (d["X3"], "add library entries for notes that ran ahead (X3)"),
                      (d["X2"], "log the planned-but-unrecorded entries (X2)"),
                      (d["X4"], "pin citation keys for pool members (X4)")):
        if keys:
            n += 1
            A(f"{n}. {msg} — {len(keys)} item(s).")
    if n == 0:
        A("*No defects outstanding.*")
    A("")
    return "\n".join(L)


def main(argv=None) -> None:
    C.utf8_stdout()
    ap = argparse.ArgumentParser(
        prog="python -m ledger.reconcile",
        description="Cross-check your registries and report real drift")
    ap.add_argument("--config")
    ap.add_argument("--no-write", action="store_true", help="print only")
    ap.add_argument("--no-zotero", action="store_true")
    a = ap.parse_args(argv)

    cfg = C.load_config(a.config)
    d = build(cfg, use_zotero=not a.no_zotero)
    md = render(cfg, d)

    print(f"cited {len(d['cited'])} | candidates {len(d['cand'])} | "
          f"library {len(d['lib'])} | notes {len(d['vault'])} | "
          f"zotero {len(d['zot']['all'])} | aliases {len(d['alias'])}")
    print("defects:")
    for tag, desc in (("X1", "cited, not in library"),
                      ("X2", "candidate, not in library"),
                      ("X3", "note, not in library"),
                      ("X4", "pool member unpinned")):
        print(f"  {tag} {desc:<28} {len(d[tag]):>4}")
    print("informational (not defects):")
    print(f"  candidate, not yet cited     {len(d['pending']):>4}")
    print(f"  read for understanding only  {len(d['learning_only']):>4}")

    if a.no_write:
        return

    out = C.out_dir(cfg, "reports") / f"reconcile_{dt.date.today().isoformat()}.md"
    out.write_text(md, encoding="utf-8")
    print(f"\nreport -> {out}")

    sources = (d["reg"].get("vault") or {}).get("sources_dir")
    if sources and Path(sources).exists():
        board = Path(sources).parent / "dashboard.md"
        board.write_text(
            f"---\ntype: dashboard\nproject: {d['reg'].get('project', '')}\n"
            f'updated: "{dt.date.today().isoformat()}"\n---\n\n'
            + md.replace("# Reconciliation report", "# Literature dashboard"),
            encoding="utf-8")
        print(f"dashboard -> {board}")


if __name__ == "__main__":
    main()
